config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  Spree::Core::Engine.routes.append do
    resources :call_messages, only: [:new, :create]
    get '/brands', :to =>'products#brand_index'
    get '/brands/:id', :to => 'products#brand_page'
    namespace :admin, path: Spree.admin_path do
      resources :call_messages
      resources :providers
      resources :brand_images
    end
  end 
          # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "/orders/remove_item" => "spree/orders#remove_line_item"
  get '/test', to: 'test#index'

  get '*id', :to => 'spree/taxons#show', :as => :categories

  #resources :call_messages#, :only => [:create, :new]
end

app/views/spree/admin/orders/_line_items.html.erb
<% if order.line_items.exists? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        Товары
      </h1>
    </div>
    <table class="table table-bordered line-items" data-hook="line-items">
      <thead>
        <tr>
          <th colspan="2"><%= Spree.t(:name) %></th>
          <th class="text-center"><%= Spree.t(:price) %></th>
          <th class="text-center"><%= Spree.t(:quantity) %></th>
          <th class="text-center"><%= Spree.t(:total_price) %></th>
        </tr>
      </thead>
      <tbody>
        <% order.line_items.each do |item| %>
          <tr class="line-item" id="line-item-<%= item.id %>">
            <td class="line-item-image image text-center">
              <%= mini_image(item.variant) %>
            </td>
            <td class="line-item-name text-center">
              <%= item.name %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
            </td>
            <td class="line-item-price text-center"><%= display_hum_price(item.price) %> руб.</td>
            <td class="line-item-qty-show text-center">
              <%= item.quantity %>
            </td>
            <td class="line-item-qty-edit is-hidden">
              <%= number_field_tag :quantity, item.quantity, min: 0, class: "line_item_quantity form-control", size: 5 %>
            </td>
            <td class="line-item-total text-center"><%= line_item_shipment_price(item, item.quantity) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Order) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_order), new_admin_order_url, class: "btn-success", icon: 'add', id: 'admin_new_order' %>
<% end if can? :create, Spree::Order %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">

    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="date-range-filter col-md-8">
          <div class="form-group">
            <%= label_tag :q_created_at_gt, Spree.t(:date_range) %>
            <div class="row no-padding-bottom">
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_gt, class: 'datepicker datepicker-from form-control', value: params[:q][:created_at_gt], placeholder: Spree.t(:start) %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>

              </div>
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_lt, class: 'datepicker datepicker-to form-control', value: params[:q][:created_at_lt], placeholder: Spree.t(:stop) %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_number_cont, Spree.t(:order_number, number: '') %>
            <%= f.text_field :number_cont, class: 'form-control js-quick-search-target' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_state_eq, Spree.t(:status) %>
            <%= f.select :state_eq, Spree::Order.state_machines[:state].states.map {|s| [Spree.t("order_state.#{s.name}"), s.value]}, {include_blank: true}, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_payment_state_eq, Spree.t(:payment_state) %>
            <%= f.select :payment_state_eq, Spree::Order::PAYMENT_STATES.map {|s| [Spree.t("payment_states.#{s}"), s]}, {include_blank: true}, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_shipment_state_eq, Spree.t(:shipment_state) %>
            <%= f.select :shipment_state_eq, Spree::Order::SHIPMENT_STATES.map {|s| [Spree.t("shipment_states.#{s}"), s]}, {include_blank: true}, class: 'select2 js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_firstname_start, Spree.t(:first_name_begins_with) %>
            <%= f.text_field :bill_address_firstname_start, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_lastname_start, Spree.t(:last_name_begins_with) %>
            <%= f.text_field :bill_address_lastname_start, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_email_cont, Spree.t(:email) %>
            <%= f.text_field :email_cont, class: 'form-control js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_line_items_variant_sku_eq, Spree.t(:sku) %>
            <%= f.text_field :line_items_variant_sku_eq, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_promotions_id_in, Spree.t(:promotion) %>
            <%= f.select :promotions_id_in, Spree::Promotion.applied.pluck(:name, :id), {include_blank: true}, class: 'select2' %>
          </div>
        </div>

        <div class="col-md-4">

          <div class="form-group">

            <div class="checkbox">
              <%= label_tag 'q_completed_at_not_null' do %>
                <%= f.check_box :completed_at_not_null, {checked: @show_only_completed}, '1', '0' %>
                <%= Spree.t(:show_only_complete_orders) %>
              <% end %>
            </div>

            <div class="checkbox">
              <%= label_tag 'q_considered_risky_eq' do %>
                <%= f.check_box :considered_risky_eq, {checked: (params[:q][:considered_risky_eq] == '1')}, '1', '' %>
                <%= Spree.t(:show_only_considered_risky) %>
              <% end %>
            </div>

          </div>

        </div>

      </div>

      <div data-hook="admin_orders_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>

    <% end %>

  </div>

<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders %>

<% if @orders.any? %>
  <table class="table" id="listing_orders" data-hook>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <th><%= sort_link @search, :created_at,     I18n.t(:created_at, scope: 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :number,           I18n.t(:number, scope: 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :customer, "Покупатель" %></th>
        <th><%= sort_link @search, :phone, "Телефон" %></th>
        <th>Адрес доставки</th>
        <th><%= sort_link @search, :email,            I18n.t(:email, scope: 'activerecord.attributes.spree/order') %></th>
        <th>Платёж</th>
        <th>Доставка</th>
        <th><%= sort_link @search, :total,            I18n.t(:total, scope: 'activerecord.attributes.spree/order') %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
        <td>
          <%= @show_only_completed ? order.completed_at.strftime("%d/%m/%Y   %T") : order.created_at.strftime("%d/%m/%Y   %T") %>
        </td>
        <td><%= link_to order.number, edit_admin_order_path(order) %></td>
        <td><%= order.bill_address.first_name%></td>
        <td><%= order.bill_address.phone%></td>
        <td><%= order.bill_address.address1%></td>
        <td>
          <% if order.user %>
            <%= link_to order.email, edit_admin_user_path(order.user) %>
          <% else %>
            <%= mail_to order.email %>
          <% end %>
          <% if order.user || order.email %>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_email_cont" data-ransack-value="<%= order.email %>"></span>
          <% end %>
        </td>
        <td><%= order.bill_address.payment_type.name if order.bill_address.payment_type%></td>
        <td><%= order.bill_address.delivery_type.name if order.bill_address.delivery_type%></td>
        <td><%= display_hum_price(order.total) %> руб.</td>
        <td class='actions actions-1' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), title: "admin_edit_#{dom_id(order)}", no_text: true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
    <%= link_to(Spree.t(:add_one), new_admin_order_url) if can? :create, Spree::Order %>!
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders, simple: true %>